// Server-side only — non importare in componenti client

export interface FlagEntry {
  flag: string;
  country: string;
  diff: 'easy' | 'medium' | 'hard';
}

export const FLAGS: FlagEntry[] = [
  // ── EASY ──────────────────────────────────────────────────────────────────
  { flag: '🇮🇹', country: 'Italia', diff: 'easy' },
  { flag: '🇫🇷', country: 'Francia', diff: 'easy' },
  { flag: '🇩🇪', country: 'Germania', diff: 'easy' },
  { flag: '🇪🇸', country: 'Spagna', diff: 'easy' },
  { flag: '🇵🇹', country: 'Portogallo', diff: 'easy' },
  { flag: '🇬🇧', country: 'Regno Unito', diff: 'easy' },
  { flag: '🇺🇸', country: 'Stati Uniti', diff: 'easy' },
  { flag: '🇨🇦', country: 'Canada', diff: 'easy' },
  { flag: '🇦🇺', country: 'Australia', diff: 'easy' },
  { flag: '🇯🇵', country: 'Giappone', diff: 'easy' },
  { flag: '🇨🇳', country: 'Cina', diff: 'easy' },
  { flag: '🇷🇺', country: 'Russia', diff: 'easy' },
  { flag: '🇧🇷', country: 'Brasile', diff: 'easy' },
  { flag: '🇲🇽', country: 'Messico', diff: 'easy' },
  { flag: '🇮🇳', country: 'India', diff: 'easy' },
  { flag: '🇦🇷', country: 'Argentina', diff: 'easy' },
  { flag: '🇿🇦', country: 'Sudafrica', diff: 'easy' },
  { flag: '🇰🇷', country: 'Corea del Sud', diff: 'easy' },
  { flag: '🇸🇦', country: 'Arabia Saudita', diff: 'easy' },
  { flag: '🇹🇷', country: 'Turchia', diff: 'easy' },
  { flag: '🇳🇱', country: 'Paesi Bassi', diff: 'easy' },
  { flag: '🇧🇪', country: 'Belgio', diff: 'easy' },
  { flag: '🇸🇪', country: 'Svezia', diff: 'easy' },
  { flag: '🇳🇴', country: 'Norvegia', diff: 'easy' },
  { flag: '🇩🇰', country: 'Danimarca', diff: 'easy' },
  { flag: '🇫🇮', country: 'Finlandia', diff: 'easy' },
  { flag: '🇨🇭', country: 'Svizzera', diff: 'easy' },
  { flag: '🇦🇹', country: 'Austria', diff: 'easy' },
  { flag: '🇵🇱', country: 'Polonia', diff: 'easy' },
  { flag: '🇬🇷', country: 'Grecia', diff: 'easy' },
  { flag: '🇪🇬', country: 'Egitto', diff: 'easy' },
  { flag: '🇮🇱', country: 'Israele', diff: 'easy' },
  { flag: '🇦🇪', country: 'Emirati Arabi', diff: 'easy' },
  { flag: '🇳🇿', country: 'Nuova Zelanda', diff: 'easy' },
  { flag: '🇵🇹', country: 'Portogallo', diff: 'easy' },
  { flag: '🇨🇿', country: 'Rep. Ceca', diff: 'easy' },
  { flag: '🇭🇺', country: 'Ungheria', diff: 'easy' },
  { flag: '🇷🇴', country: 'Romania', diff: 'easy' },
  { flag: '🇺🇦', country: 'Ucraina', diff: 'easy' },
  { flag: '🇮🇪', country: 'Irlanda', diff: 'easy' },
  { flag: '🇲🇦', country: 'Marocco', diff: 'easy' },
  { flag: '🇰🇪', country: 'Kenya', diff: 'easy' },
  { flag: '🇳🇬', country: 'Nigeria', diff: 'easy' },
  { flag: '🇨🇴', country: 'Colombia', diff: 'easy' },
  { flag: '🇨🇱', country: 'Cile', diff: 'easy' },
  { flag: '🇵🇪', country: 'Perù', diff: 'easy' },
  { flag: '🇹🇭', country: 'Thailandia', diff: 'easy' },
  { flag: '🇻🇳', country: 'Vietnam', diff: 'easy' },
  { flag: '🇮🇩', country: 'Indonesia', diff: 'easy' },
  { flag: '🇵🇭', country: 'Filippine', diff: 'easy' },
  // ── MEDIUM ────────────────────────────────────────────────────────────────
  { flag: '🇺🇿', country: 'Uzbekistan', diff: 'medium' },
  { flag: '🇰🇿', country: 'Kazakhstan', diff: 'medium' },
  { flag: '🇬🇪', country: 'Georgia', diff: 'medium' },
  { flag: '🇦🇲', country: 'Armenia', diff: 'medium' },
  { flag: '🇦🇿', country: 'Azerbaijan', diff: 'medium' },
  { flag: '🇲🇾', country: 'Malaysia', diff: 'medium' },
  { flag: '🇸🇬', country: 'Singapore', diff: 'medium' },
  { flag: '🇧🇩', country: 'Bangladesh', diff: 'medium' },
  { flag: '🇵🇰', country: 'Pakistan', diff: 'medium' },
  { flag: '🇮🇶', country: 'Iraq', diff: 'medium' },
  { flag: '🇮🇷', country: 'Iran', diff: 'medium' },
  { flag: '🇯🇴', country: 'Giordania', diff: 'medium' },
  { flag: '🇱🇧', country: 'Libano', diff: 'medium' },
  { flag: '🇶🇦', country: 'Qatar', diff: 'medium' },
  { flag: '🇰🇼', country: 'Kuwait', diff: 'medium' },
  { flag: '🇧🇭', country: 'Bahrein', diff: 'medium' },
  { flag: '🇴🇲', country: 'Oman', diff: 'medium' },
  { flag: '🇾🇪', country: 'Yemen', diff: 'medium' },
  { flag: '🇸🇾', country: 'Siria', diff: 'medium' },
  { flag: '🇭🇷', country: 'Croazia', diff: 'medium' },
  { flag: '🇷🇸', country: 'Serbia', diff: 'medium' },
  { flag: '🇸🇮', country: 'Slovenia', diff: 'medium' },
  { flag: '🇸🇰', country: 'Slovacchia', diff: 'medium' },
  { flag: '🇧🇬', country: 'Bulgaria', diff: 'medium' },
  { flag: '🇧🇾', country: 'Bielorussia', diff: 'medium' },
  { flag: '🇱🇹', country: 'Lituania', diff: 'medium' },
  { flag: '🇱🇻', country: 'Lettonia', diff: 'medium' },
  { flag: '🇪🇪', country: 'Estonia', diff: 'medium' },
  { flag: '🇦🇱', country: 'Albania', diff: 'medium' },
  { flag: '🇲🇰', country: 'Macedonia del Nord', diff: 'medium' },
  { flag: '🇧🇦', country: 'Bosnia ed Erzegovina', diff: 'medium' },
  { flag: '🇲🇪', country: 'Montenegro', diff: 'medium' },
  { flag: '🇹🇳', country: 'Tunisia', diff: 'medium' },
  { flag: '🇱🇾', country: 'Libia', diff: 'medium' },
  { flag: '🇩🇿', country: 'Algeria', diff: 'medium' },
  { flag: '🇪🇹', country: 'Etiopia', diff: 'medium' },
  { flag: '🇬🇭', country: 'Ghana', diff: 'medium' },
  { flag: '🇸🇳', country: 'Senegal', diff: 'medium' },
  { flag: '🇨🇮', country: "Costa d'Avorio", diff: 'medium' },
  { flag: '🇨🇲', country: 'Camerun', diff: 'medium' },
  { flag: '🇹🇿', country: 'Tanzania', diff: 'medium' },
  { flag: '🇺🇬', country: 'Uganda', diff: 'medium' },
  { flag: '🇲🇿', country: 'Mozambico', diff: 'medium' },
  { flag: '🇿🇲', country: 'Zambia', diff: 'medium' },
  { flag: '🇿🇼', country: 'Zimbabwe', diff: 'medium' },
  { flag: '🇧🇴', country: 'Bolivia', diff: 'medium' },
  { flag: '🇵🇾', country: 'Paraguay', diff: 'medium' },
  { flag: '🇺🇾', country: 'Uruguay', diff: 'medium' },
  { flag: '🇪🇨', country: 'Ecuador', diff: 'medium' },
  { flag: '🇻🇪', country: 'Venezuela', diff: 'medium' },
  { flag: '🇨🇷', country: 'Costa Rica', diff: 'medium' },
  { flag: '🇨🇺', country: 'Cuba', diff: 'medium' },
  { flag: '🇩🇴', country: 'Rep. Dominicana', diff: 'medium' },
  { flag: '🇮🇸', country: 'Islanda', diff: 'medium' },
  { flag: '🇲🇳', country: 'Mongolia', diff: 'medium' },
  { flag: '🇱🇰', country: 'Sri Lanka', diff: 'medium' },
  { flag: '🇳🇵', country: 'Nepal', diff: 'medium' },
  { flag: '🇰🇭', country: 'Cambogia', diff: 'medium' },
  { flag: '🇲🇲', country: 'Myanmar', diff: 'medium' },
  { flag: '🇱🇦', country: 'Laos', diff: 'medium' },
  { flag: '🇱🇺', country: 'Lussemburgo', diff: 'medium' },
  { flag: '🇲🇹', country: 'Malta', diff: 'medium' },
  { flag: '🇨🇾', country: 'Cipro', diff: 'medium' },
  { flag: '🇲🇨', country: 'Monaco', diff: 'medium' },
  { flag: '🇸🇲', country: 'San Marino', diff: 'medium' },
  { flag: '🇻🇦', country: 'Città del Vaticano', diff: 'medium' },
  { flag: '🇯🇲', country: 'Giamaica', diff: 'medium' },
  { flag: '🇵🇦', country: 'Panama', diff: 'medium' },
  { flag: '🇰🇵', country: 'Corea del Nord', diff: 'medium' },
  { flag: '🇸🇻', country: 'El Salvador', diff: 'medium' },
  { flag: '🇵🇷', country: 'Porto Rico', diff: 'medium' },
  // ── HARD ──────────────────────────────────────────────────────────────────
  { flag: '🇧🇹', country: 'Bhutan', diff: 'hard' },
  { flag: '🇹🇱', country: 'Timor Est', diff: 'hard' },
  { flag: '🇸🇷', country: 'Suriname', diff: 'hard' },
  { flag: '🇬🇾', country: 'Guyana', diff: 'hard' },
  { flag: '🇫🇯', country: 'Figi', diff: 'hard' },
  { flag: '🇵🇬', country: 'Papua Nuova Guinea', diff: 'hard' },
  { flag: '🇸🇧', country: 'Isole Salomone', diff: 'hard' },
  { flag: '🇻🇺', country: 'Vanuatu', diff: 'hard' },
  { flag: '🇼🇸', country: 'Samoa', diff: 'hard' },
  { flag: '🇹🇴', country: 'Tonga', diff: 'hard' },
  { flag: '🇲🇬', country: 'Madagascar', diff: 'hard' },
  { flag: '🇲🇼', country: 'Malawi', diff: 'hard' },
  { flag: '🇷🇼', country: 'Rwanda', diff: 'hard' },
  { flag: '🇧🇮', country: 'Burundi', diff: 'hard' },
  { flag: '🇩🇯', country: 'Gibuti', diff: 'hard' },
  { flag: '🇪🇷', country: 'Eritrea', diff: 'hard' },
  { flag: '🇸🇴', country: 'Somalia', diff: 'hard' },
  { flag: '🇸🇸', country: 'Sudan del Sud', diff: 'hard' },
  { flag: '🇨🇫', country: 'Rep. Centrafricana', diff: 'hard' },
  { flag: '🇹🇩', country: 'Ciad', diff: 'hard' },
  { flag: '🇳🇪', country: 'Niger', diff: 'hard' },
  { flag: '🇲🇱', country: 'Mali', diff: 'hard' },
  { flag: '🇧🇫', country: 'Burkina Faso', diff: 'hard' },
  { flag: '🇬🇳', country: 'Guinea', diff: 'hard' },
  { flag: '🇸🇱', country: 'Sierra Leone', diff: 'hard' },
  { flag: '🇱🇷', country: 'Liberia', diff: 'hard' },
  { flag: '🇹🇬', country: 'Togo', diff: 'hard' },
  { flag: '🇧🇯', country: 'Benin', diff: 'hard' },
  { flag: '🇲🇷', country: 'Mauritania', diff: 'hard' },
  { flag: '🇬🇲', country: 'Gambia', diff: 'hard' },
  { flag: '🇰🇬', country: 'Kirghizistan', diff: 'hard' },
  { flag: '🇹🇯', country: 'Tagikistan', diff: 'hard' },
  { flag: '🇹🇲', country: 'Turkmenistan', diff: 'hard' },
  { flag: '🇦🇫', country: 'Afghanistan', diff: 'hard' },
  { flag: '🇲🇻', country: 'Maldive', diff: 'hard' },
  { flag: '🇰🇮', country: 'Kiribati', diff: 'hard' },
  { flag: '🇳🇷', country: 'Nauru', diff: 'hard' },
  { flag: '🇵🇼', country: 'Palau', diff: 'hard' },
  { flag: '🇫🇲', country: 'Micronesia', diff: 'hard' },
  { flag: '🇲🇭', country: 'Isole Marshall', diff: 'hard' },
  { flag: '🇦🇩', country: 'Andorra', diff: 'hard' },
  { flag: '🇱🇮', country: 'Liechtenstein', diff: 'hard' },
  { flag: '🇧🇳', country: 'Brunei', diff: 'hard' },
  { flag: '🇦🇴', country: 'Angola', diff: 'hard' },
  { flag: '🇳🇦', country: 'Namibia', diff: 'hard' },
  { flag: '🇧🇼', country: 'Botswana', diff: 'hard' },
  { flag: '🇱🇸', country: 'Lesotho', diff: 'hard' },
  { flag: '🇸🇿', country: 'Eswatini', diff: 'hard' }, // Ex Swaziland
  { flag: '🇬🇦', country: 'Gabon', diff: 'hard' },
  { flag: '🇨🇬', country: 'Rep. del Congo', diff: 'hard' },
  { flag: '🇨🇩', country: 'Rep. Dem. del Congo', diff: 'hard' },
  { flag: '🇬🇶', country: 'Guinea Equatoriale', diff: 'hard' },
  { flag: '🇬🇼', country: 'Guinea-Bissau', diff: 'hard' },
  { flag: '🇨🇻', country: 'Capo Verde', diff: 'hard' },
  { flag: '🇰🇲', country: 'Comore', diff: 'hard' },
  { flag: '🇸🇨', country: 'Seychelles', diff: 'hard' },
  { flag: '🇲🇺', country: 'Mauritius', diff: 'hard' },
  { flag: '🇸🇹', country: 'São Tomé e Príncipe', diff: 'hard' },
  { flag: '🇧🇿', country: 'Belize', diff: 'hard' },
  { flag: '🇬🇹', country: 'Guatemala', diff: 'hard' },
  { flag: '🇭🇳', country: 'Honduras', diff: 'hard' },
  { flag: '🇳🇮', country: 'Nicaragua', diff: 'hard' },
  { flag: '🇧🇸', country: 'Bahamas', diff: 'hard' },
  { flag: '🇭🇹', country: 'Haiti', diff: 'hard' },
  { flag: '🇹🇹', country: 'Trinidad e Tobago', diff: 'hard' },
  { flag: '🇧🇧', country: 'Barbados', diff: 'hard' },
  { flag: '🇬🇩', country: 'Grenada', diff: 'hard' },
  { flag: '🇩🇲', country: 'Dominica', diff: 'hard' },
  { flag: '🇱🇨', country: 'Santa Lucia', diff: 'hard' },
  { flag: '🇻🇨', country: 'Saint Vincent e Grenadine', diff: 'hard' },
  { flag: '🇰🇳', country: 'Saint Kitts e Nevis', diff: 'hard' },
  { flag: '🇦🇬', country: 'Antigua e Barbuda', diff: 'hard' },
  { flag: '🇹🇻', country: 'Tuvalu', diff: 'hard' }
];

export function getFlagRound(diff: 'easy' | 'medium' | 'hard', count = 10) {
  const pool = FLAGS.filter(f => f.diff === diff);
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const selected = shuffled.slice(0, Math.min(count, shuffled.length));

  const allCountries = FLAGS.map(f => f.country);

  return selected.map(entry => {
    const wrongs = allCountries
      .filter(c => c !== entry.country)
      .sort(() => Math.random() - 0.5)
      .slice(0, 3);
    const opts = [...wrongs, entry.country].sort(() => Math.random() - 0.5) as [string, string, string, string];
    const a = opts.indexOf(entry.country) as 0 | 1 | 2 | 3;
    return { flag: entry.flag, country: entry.country, opts, a };
  });
}
