// Server-side only — non importare mai in componenti client
// Aggiungere domande seguendo il pattern esistente

export interface BankQuestion {
  q: string;
  opts: [string, string, string, string];
  a: 0 | 1 | 2 | 3;
  diff: 'easy' | 'medium' | 'hard';
  emoji?: string;
}

export const BANK: BankQuestion[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // EASY — Capitali famose
  // ─────────────────────────────────────────────────────────────────────────
  { q: "Qual è la capitale d'Italia?", opts: ['Milano', 'Napoli', 'Roma', 'Torino'], a: 2, diff: 'easy', emoji: '🇮🇹' },
  { q: "Qual è la capitale del Regno Unito?", opts: ['Manchester', 'Edimburgo', 'Birmingham', 'Londra'], a: 3, diff: 'easy', emoji: '🇬🇧' },
  { q: "Qual è la capitale degli Stati Uniti?", opts: ['New York', 'Los Angeles', 'Washington D.C.', 'Chicago'], a: 2, diff: 'easy', emoji: '🇺🇸' },
  { q: "Qual è la capitale della Cina?", opts: ['Shanghai', 'Hong Kong', 'Guangzhou', 'Pechino'], a: 3, diff: 'easy', emoji: '🇨🇳' },
  { q: "Qual è la capitale della Russia?", opts: ['San Pietroburgo', 'Mosca', 'Novosibirsk', 'Kazan'], a: 1, diff: 'easy', emoji: '🇷🇺' },
  { q: "Qual è la capitale dell'India?", opts: ['Mumbai', 'Kolkata', 'Bangalore', 'Nuova Delhi'], a: 3, diff: 'easy', emoji: '🇮🇳' },
  { q: "Qual è la capitale del Brasile?", opts: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'], a: 2, diff: 'easy', emoji: '🇧🇷' },
  { q: "Qual è la capitale del Messico?", opts: ['Guadalajara', 'Monterrey', 'Cancún', 'Città del Messico'], a: 3, diff: 'easy', emoji: '🇲🇽' },
  { q: "Qual è la capitale della Corea del Sud?", opts: ['Busan', 'Seul', 'Incheon', 'Daegu'], a: 1, diff: 'easy', emoji: '🇰🇷' },
  { q: "Qual è la capitale della Svezia?", opts: ['Göteborg', 'Malmö', 'Stoccolma', 'Uppsala'], a: 2, diff: 'easy', emoji: '🇸🇪' },
  { q: "Qual è la capitale della Norvegia?", opts: ['Bergen', 'Oslo', 'Trondheim', 'Stavanger'], a: 1, diff: 'easy', emoji: '🇳🇴' },
  { q: "Qual è la capitale della Danimarca?", opts: ['Aarhus', 'Odense', 'Copenaghen', 'Aalborg'], a: 2, diff: 'easy', emoji: '🇩🇰' },
  { q: "Qual è la capitale della Finlandia?", opts: ['Tampere', 'Helsinki', 'Turku', 'Espoo'], a: 1, diff: 'easy', emoji: '🇫🇮' },
  { q: "Qual è la capitale dell'Austria?", opts: ['Salisburgo', 'Graz', 'Vienna', 'Linz'], a: 2, diff: 'easy', emoji: '🇦🇹' },
  { q: "Qual è la capitale della Svizzera?", opts: ['Zurigo', 'Ginevra', 'Losanna', 'Berna'], a: 3, diff: 'easy', emoji: '🇨🇭' },
  { q: "Qual è la capitale del Belgio?", opts: ['Anversa', 'Bruxelles', 'Gand', 'Liegi'], a: 1, diff: 'easy', emoji: '🇧🇪' },
  { q: "Qual è la capitale della Polonia?", opts: ['Cracovia', 'Varsavia', 'Breslavia', 'Poznań'], a: 1, diff: 'easy', emoji: '🇵🇱' },
  { q: "Qual è la capitale della Repubblica Ceca?", opts: ['Brno', 'Ostrava', 'Praga', 'Pilsen'], a: 2, diff: 'easy', emoji: '🇨🇿' },
  { q: "Qual è la capitale dell'Ungheria?", opts: ['Debrecen', 'Pécs', 'Miskolc', 'Budapest'], a: 3, diff: 'easy', emoji: '🇭🇺' },
  { q: "Qual è la capitale della Romania?", opts: ['Cluj', 'Timișoara', 'Iași', 'Bucarest'], a: 3, diff: 'easy', emoji: '🇷🇴' },
  { q: "Qual è la capitale della Grecia?", opts: ['Salonicco', 'Patrasso', 'Atene', 'Iraklion'], a: 2, diff: 'easy', emoji: '🇬🇷' },
  { q: "Qual è la capitale della Turchia?", opts: ['Istanbul', 'Smirne', 'Bursa', 'Ankara'], a: 3, diff: 'easy', emoji: '🇹🇷' },
  { q: "Qual è la capitale del Marocco?", opts: ['Casablanca', 'Marrakech', 'Fes', 'Rabat'], a: 3, diff: 'easy', emoji: '🇲🇦' },
  { q: "Qual è la capitale del Kenya?", opts: ['Mombasa', 'Kisumu', 'Nairobi', 'Nakuru'], a: 2, diff: 'easy', emoji: '🇰🇪' },
  // EASY — Monumenti & Attrazioni
  { q: "In quale paese si trova Big Ben?", opts: ['Francia', 'Italia', 'Germania', 'Regno Unito'], a: 3, diff: 'easy', emoji: '🕰️' },
  { q: "In quale paese si trova la Muraglia Cinese?", opts: ['Mongolia', 'Giappone', 'Corea del Sud', 'Cina'], a: 3, diff: 'easy', emoji: '🏯' },
  { q: "In quale paese si trova il Taj Mahal?", opts: ['Pakistan', 'Bangladesh', 'India', 'Sri Lanka'], a: 2, diff: 'easy', emoji: '🕌' },
  { q: "In quale paese si trova la Piramide di Giza?", opts: ['Sudan', 'Libia', 'Tunisia', 'Egitto'], a: 3, diff: 'easy', emoji: '🔺' },
  { q: "In quale paese si trova Stonehenge?", opts: ['Irlanda', 'Scozia', 'Galles', 'Inghilterra'], a: 3, diff: 'easy', emoji: '🪨' },
  { q: "In quale paese si trova la Torre di Pisa?", opts: ['Spagna', 'Francia', 'Italia', 'Portogallo'], a: 2, diff: 'easy', emoji: '🗼' },
  { q: "In quale paese si trova il Colosseo?", opts: ['Grecia', 'Croazia', 'Italia', 'Malta'], a: 2, diff: 'easy', emoji: '🏟️' },
  // EASY — Geografia base
  { q: "Qual è la capitale della Germania?", opts: ['Monaco', 'Amburgo', 'Berlino', 'Francoforte'], a: 2, diff: 'easy', emoji: '🇩🇪' },
  { q: "Qual è la capitale dell'Irlanda?", opts: ['Belfast', 'Dublino', 'Cork', 'Galway'], a: 1, diff: 'easy', emoji: '🇮🇪' },
  { q: "In quale paese si trova la Statua della Libertà?", opts: ['Francia', 'Regno Unito', 'Stati Uniti', 'Canada'], a: 2, diff: 'easy', emoji: '🗽' },
  { q: "Quale lingua si parla ufficialmente in Argentina?", opts: ['Portoghese', 'Italiano', 'Spagnolo', 'Francese'], a: 2, diff: 'easy', emoji: '🇦🇷' },
  { q: "In quale paese si trova la città di Dubai?", opts: ['Arabia Saudita', 'Emirati Arabi', 'Qatar', 'Oman'], a: 1, diff: 'easy', emoji: '🏙️' },
  { q: "Quale paese è famoso per i suoi canali e mulini a vento?", opts: ['Belgio', 'Danimarca', 'Paesi Bassi', 'Svezia'], a: 2, diff: 'easy', emoji: '🇳🇱' },
  { q: "Qual è la capitale della Francia?", opts: ['Lione', 'Marsiglia', 'Parigi', 'Nizza'], a: 2, diff: 'easy', emoji: '🇫🇷' },
  { q: "In quale continente si trova l'Egitto?", opts: ['Asia', 'Europa', 'Africa', 'Oceania'], a: 2, diff: 'easy', emoji: '🌍' },
  { q: "Quale continente è il più grande?", opts: ['Africa', 'America', 'Europa', 'Asia'], a: 3, diff: 'easy', emoji: '🌏' },
  { q: "Quale continente è il più piccolo?", opts: ['Europa', 'Antartide', 'Australia', 'Sud America'], a: 2, diff: 'easy', emoji: '🌏' },
  { q: "Quale è il monte più alto del mondo?", opts: ['K2', 'Kangchenjunga', 'Monte Bianco', 'Everest'], a: 3, diff: 'easy', emoji: '⛰️' },
  { q: "Quale è il paese più grande del mondo?", opts: ['Cina', 'USA', 'Canada', 'Russia'], a: 3, diff: 'easy', emoji: '🌍' },
  { q: "Quale è la lingua più parlata al mondo?", opts: ['Inglese', 'Hindi', 'Mandarino', 'Spagnolo'], a: 2, diff: 'easy', emoji: '🗣️' },
  { q: "Qual è il paese più popoloso del mondo?", opts: ['Cina', 'USA', 'India', 'Indonesia'], a: 2, diff: 'easy', emoji: '👥' },
  { q: "Qual è la città più popolosa del mondo?", opts: ['Pechino', 'Shanghai', 'Tokyo', 'Delhi'], a: 2, diff: 'easy', emoji: '🏙️' },
  // EASY — Monete
  { q: "Quale moneta usa il Regno Unito?", opts: ['Euro', 'Franco', 'Corona', 'Sterlina'], a: 3, diff: 'easy', emoji: '💷' },
  { q: "Quale moneta usa la Svizzera?", opts: ['Euro', 'Scellino', 'Franco svizzero', 'Corona'], a: 2, diff: 'easy', emoji: '🇨🇭' },
  { q: "Quale moneta usa la Russia?", opts: ['Grivna', 'Lev', 'Rublo', 'Tenge'], a: 2, diff: 'easy', emoji: '🇷🇺' },
  { q: "Quale moneta usa il Giappone?", opts: ['Won', 'Yuan', 'Baht', 'Yen'], a: 3, diff: 'easy', emoji: '💴' },
  { q: "Quale moneta usa gli USA?", opts: ['Sterlina', 'Franco', 'Dollaro', 'Euro'], a: 2, diff: 'easy', emoji: '💵' },
  { q: "Quale moneta usa il Brasile?", opts: ['Peso', 'Sol', 'Real brasiliano', 'Dolar'], a: 2, diff: 'easy', emoji: '🇧🇷' },
  // EASY — Travel facts
  { q: "Quale paese è più visitato al mondo?", opts: ['USA', 'Spagna', 'Francia', 'Italia'], a: 2, diff: 'easy', emoji: '✈️' },
  { q: "Quale lingua si parla in Brasile?", opts: ['Spagnolo', 'Francese', 'Portoghese', 'Italiano'], a: 2, diff: 'easy', emoji: '🗣️' },
  { q: "Quale lingua si parla in Australia?", opts: ['Inglese', 'Francese', 'Spagnolo', 'Tedesco'], a: 0, diff: 'easy', emoji: '🇦🇺' },
  { q: "Quante stelle ha la bandiera degli USA?", opts: ['48', '49', '50', '52'], a: 2, diff: 'easy', emoji: '🇺🇸' },
  { q: "Quale paese ha la foglia d'acero sulla bandiera?", opts: ['Australia', 'Nuova Zelanda', 'Canada', 'USA'], a: 2, diff: 'easy', emoji: '🍁' },
  { q: "Quale paese ha la bandiera con la croce rossa su sfondo bianco?", opts: ['Svezia', 'Norvegia', 'Danimarca', 'Svizzera'], a: 3, diff: 'easy', emoji: '🏥' },
  { q: "Quale paese ha la bandiera con la Union Jack?", opts: ['Canada', 'Australia', 'Irlanda', 'Nuova Zelanda'], a: 1, diff: 'easy', emoji: '🇦🇺' },
  { q: "Quale oceano bagna le coste dell'Italia?", opts: ['Atlantico', 'Pacifico', 'Artico', 'Mediterraneo'], a: 3, diff: 'easy', emoji: '🌊' },
  { q: "In quale continente si trova il Messico?", opts: ['Sud America', 'Nord America', 'Caraibi', 'America Centrale'], a: 1, diff: 'easy', emoji: '🌎' },
  { q: "In quale continente si trova il Giappone?", opts: ['Oceania', 'Africa', 'Asia', 'Europa'], a: 2, diff: 'easy', emoji: '🌏' },
  { q: "Quale è la capitale dell'Australia?", opts: ['Sydney', 'Melbourne', 'Brisbane', 'Canberra'], a: 3, diff: 'easy', emoji: '🇦🇺' },
  { q: "Quale stretto separa Europa da Africa?", opts: ['Stretto di Sicilia', 'Stretto di Messina', 'Stretto di Ormuz', 'Stretto di Gibilterra'], a: 3, diff: 'easy', emoji: '🌊' },
  { q: "In quale paese si trova la Sagrada Família?", opts: ['Portogallo', 'Spagna', 'Italia', 'Francia'], a: 1, diff: 'easy', emoji: '⛪' },
  { q: "Qual è la capitale della Spagna?", opts: ['Roma', 'Lisbona', 'Madrid', 'Barcellona'], a: 2, diff: 'easy', emoji: '🇪🇸' },
  { q: "Qual è l'oceano più grande del mondo?", opts: ['Atlantico', 'Indiano', 'Artico', 'Pacifico'], a: 3, diff: 'easy', emoji: '🌊' },
  { q: "In quale paese si trova la Torre Eiffel?", opts: ['Italia', 'Spagna', 'Germania', 'Francia'], a: 3, diff: 'easy', emoji: '🗼' },
  { q: "In quale continente si trova il Brasile?", opts: ['Africa', 'Asia', 'Nord America', 'Sud America'], a: 3, diff: 'easy', emoji: '🇧🇷' },
  { q: "In quale paese si trova il Partenone?", opts: ['Italia', 'Turchia', 'Grecia', 'Egitto'], a: 2, diff: 'easy', emoji: '🏛️' },
  { q: "Qual è la capitale dell'Egitto?", opts: ['Alessandria', 'Luxor', 'Il Cairo', 'Assuan'], a: 2, diff: 'easy', emoji: '🇪🇬' },

  // ─────────────────────────────────────────────────────────────────────────
  // MEDIUM — Capitali meno ovvie
  // ─────────────────────────────────────────────────────────────────────────
  { q: "Qual è la capitale del Canada?", opts: ['Toronto', 'Vancouver', 'Ottawa', 'Montréal'], a: 2, diff: 'medium', emoji: '🇨🇦' },
  { q: "Qual è la capitale della Nuova Zelanda?", opts: ['Auckland', 'Christchurch', 'Hamilton', 'Wellington'], a: 3, diff: 'medium', emoji: '🇳🇿' },
  { q: "Qual è la capitale del Portogallo?", opts: ['Porto', 'Faro', 'Coimbra', 'Lisbona'], a: 3, diff: 'medium', emoji: '🇵🇹' },
  { q: "Qual è la capitale dell'Argentina?", opts: ['Santiago', 'Lima', 'Montevideo', 'Buenos Aires'], a: 3, diff: 'medium', emoji: '🇦🇷' },
  { q: "Qual è la capitale dei Paesi Bassi?", opts: ['Rotterdam', 'Utrecht', "L'Aia", 'Amsterdam'], a: 3, diff: 'medium', emoji: '🇳🇱' },
  { q: "Qual è la capitale del Sud Africa?", opts: ['Johannesburg', 'Durban', 'Città del Capo', 'Pretoria'], a: 3, diff: 'medium', emoji: '🇿🇦' },
  { q: "Qual è la capitale della Colombia?", opts: ['Medellín', 'Cali', 'Bogotà', 'Barranquilla'], a: 2, diff: 'medium', emoji: '🇨🇴' },
  { q: "Qual è la capitale del Vietnam?", opts: ['Ho Chi Minh', 'Danang', 'Hue', 'Hanoi'], a: 3, diff: 'medium', emoji: '🇻🇳' },
  { q: "Qual è la capitale della Tailandia?", opts: ['Chiang Mai', 'Pattaya', 'Phuket', 'Bangkok'], a: 3, diff: 'medium', emoji: '🇹🇭' },
  { q: "Qual è la capitale della Malaysia?", opts: ['Penang', 'Johor Bahru', 'Kuala Lumpur', 'Malacca'], a: 2, diff: 'medium', emoji: '🇲🇾' },
  { q: "Qual è la capitale delle Filippine?", opts: ['Cebu', 'Davao', 'Quezon City', 'Manila'], a: 3, diff: 'medium', emoji: '🇵🇭' },
  { q: "Qual è la capitale dell'Indonesia?", opts: ['Surabaya', 'Bali', 'Bandung', 'Giacarta'], a: 3, diff: 'medium', emoji: '🇮🇩' },
  { q: "Qual è la capitale della Croazia?", opts: ['Spalato', 'Dubrovnik', 'Zara', 'Zagabria'], a: 3, diff: 'medium', emoji: '🇭🇷' },
  { q: "Qual è la capitale della Scozia?", opts: ['Glasgow', 'Aberdeen', 'Inverness', 'Edimburgo'], a: 3, diff: 'medium', emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { q: "Qual è la capitale del Perù?", opts: ['Arequipa', 'Cusco', 'Lima', 'Trujillo'], a: 2, diff: 'medium', emoji: '🇵🇪' },
  { q: "Qual è la capitale della Nigeria?", opts: ['Lagos', 'Kano', 'Ibadan', 'Abuja'], a: 3, diff: 'medium', emoji: '🇳🇬' },
  { q: "Qual è la capitale dell'Iran?", opts: ['Isfahan', 'Mashhad', 'Teheran', 'Shiraz'], a: 2, diff: 'medium', emoji: '🇮🇷' },
  { q: "Qual è la capitale dell'Arabia Saudita?", opts: ['Gedda', 'Mecca', 'Medina', 'Riyadh'], a: 3, diff: 'medium', emoji: '🇸🇦' },
  { q: "Qual è la capitale degli Emirati Arabi?", opts: ['Dubai', 'Sharjah', 'Abu Dhabi', 'Ajman'], a: 2, diff: 'medium', emoji: '🇦🇪' },
  { q: "Qual è la capitale dell'Israele?", opts: ['Tel Aviv', 'Haifa', 'Gerusalemme', 'Eilat'], a: 2, diff: 'medium', emoji: '🇮🇱' },
  // MEDIUM — Cultura & Gastronomia
  { q: "In quale paese si trova Machu Picchu?", opts: ['Bolivia', 'Ecuador', 'Colombia', 'Perù'], a: 3, diff: 'medium', emoji: '🏔️' },
  { q: "Quale paese ha regalato la Statua della Libertà agli USA?", opts: ['Gran Bretagna', 'Germania', 'Spagna', 'Francia'], a: 3, diff: 'medium', emoji: '🗽' },
  { q: "In quale paese si trova Angkor Wat?", opts: ['Thailandia', 'Cambogia', 'Vietnam', 'Laos'], a: 1, diff: 'medium', emoji: '🏯' },
  { q: "In quale paese si trova Petra?", opts: ['Arabia Saudita', 'Egitto', 'Israele', 'Giordania'], a: 3, diff: 'medium', emoji: '🏺' },
  { q: "In quale paese si trova Zanzibar?", opts: ['Kenya', 'Mozambico', 'Tanzania', 'Madagascar'], a: 2, diff: 'medium', emoji: '🏝️' },
  { q: "In quale paese è nato il sushi?", opts: ['Cina', 'Corea del Sud', 'Giappone', 'Tailandia'], a: 2, diff: 'medium', emoji: '🍣' },
  { q: "Quale piatto è tipico della Spagna?", opts: ['Risotto', 'Paella', 'Moussaka', 'Goulash'], a: 1, diff: 'medium', emoji: '🥘' },
  { q: "Quale piatto è tipico del Giappone?", opts: ['Kimchi', 'Pad Thai', 'Ramen', 'Pho'], a: 2, diff: 'medium', emoji: '🍜' },
  { q: "Quale piatto è tipico della Grecia?", opts: ['Baklava', 'Hummus', 'Moussaka', 'Shawarma'], a: 2, diff: 'medium', emoji: '🍽️' },
  { q: "In quale paese è nata la pizza?", opts: ['Francia', 'Grecia', 'Italia', 'Spagna'], a: 2, diff: 'medium', emoji: '🍕' },
  { q: "Quale paese produce il Parmigiano Reggiano DOP?", opts: ['Svizzera', 'Francia', 'Olanda', 'Italia'], a: 3, diff: 'medium', emoji: '🧀' },
  { q: "Quale paese produce il vino Champagne?", opts: ['Italia', 'Spagna', 'Francia', 'Germania'], a: 2, diff: 'medium', emoji: '🥂' },
  // MEDIUM — Aviazione & Travel
  { q: "Quale aeroporto ha il codice IATA 'JFK'?", opts: ['Los Angeles', 'Chicago', 'Miami', 'New York'], a: 3, diff: 'medium', emoji: '✈️' },
  { q: "Quale aeroporto ha il codice IATA 'CDG'?", opts: ['Londra', 'Berlino', 'Amsterdam', 'Parigi'], a: 3, diff: 'medium', emoji: '✈️' },
  { q: "Quale aeroporto ha il codice IATA 'FCO'?", opts: ['Milano', 'Roma', 'Napoli', 'Torino'], a: 1, diff: 'medium', emoji: '✈️' },
  { q: "Quale aeroporto ha il codice IATA 'DXB'?", opts: ['Doha', 'Abu Dhabi', 'Dubai', 'Riyadh'], a: 2, diff: 'medium', emoji: '✈️' },
  { q: "Quale compagnia aerea usa il codice IATA 'EK'?", opts: ['Etihad', 'Emirates', 'Qatar Airways', 'Turkish'], a: 1, diff: 'medium', emoji: '✈️' },
  { q: "Quale compagnia aerea usa il codice IATA 'QR'?", opts: ['Etihad', 'Emirates', 'Qatar Airways', 'Air Arabia'], a: 2, diff: 'medium', emoji: '✈️' },
  { q: "Quale compagnia aerea usa il codice IATA 'LH'?", opts: ['Swiss', 'Austrian', 'Air Berlin', 'Lufthansa'], a: 3, diff: 'medium', emoji: '✈️' },
  { q: "Quale compagnia aerea usa il codice IATA 'FR'?", opts: ['Air France', 'Wizzair', 'Ryanair', 'EasyJet'], a: 2, diff: 'medium', emoji: '✈️' },
  { q: "In quale paese si trova la Grande Barriera Corallina?", opts: ['Filippine', 'Indonesia', 'Australia', 'Brasile'], a: 2, diff: 'medium', emoji: '🪸' },
  { q: "Qual è il confine terrestre più lungo del mondo?", opts: ['Russia-Cina', 'USA-Canada', 'Cina-Mongolia', 'Russia-Kazakhstan'], a: 1, diff: 'medium', emoji: '🗺️' },
  { q: "Qual è la valuta della Tailandia?", opts: ['Ringgit', 'Dong', 'Kip', 'Baht'], a: 3, diff: 'medium', emoji: '🇹🇭' },
  { q: "Quale stretto unisce il Mar Rosso al Mar Arabico?", opts: ['Stretto di Ormuz', 'Stretto di Malacca', 'Stretto di Bab-el-Mandeb', 'Canale di Suez'], a: 2, diff: 'medium', emoji: '🌊' },
  { q: "In quale paese si trova il lago Titicaca?", opts: ['Cile', 'Bolivia e Perù', 'Colombia', 'Ecuador'], a: 1, diff: 'medium', emoji: '🏔️' },
  { q: "In quale paese si trova Angkor Wat?", opts: ['Laos', 'Birmania', 'Vietnam', 'Cambogia'], a: 3, diff: 'medium', emoji: '🏯' },
  { q: "Quale paese ha il maggior numero di siti UNESCO?", opts: ['Francia', 'Spagna', 'Cina', 'Italia'], a: 3, diff: 'medium', emoji: '🏛️' },
  { q: "Quale è il deserto più grande del mondo?", opts: ['Sahara', 'Gobi', 'Atacama', 'Antartide'], a: 3, diff: 'medium', emoji: '🏜️' },
  { q: "Quale è il fiume più lungo del mondo?", opts: ['Amazzonia', 'Mississippi', 'Yang-tze', 'Nilo'], a: 3, diff: 'medium', emoji: '🏞️' },
  { q: "Quale valuta usa Israele?", opts: ['Dinar', 'Lira', 'Shekel', 'Pound'], a: 2, diff: 'medium', emoji: '🇮🇱' },
  { q: "Quale valuta usa la Turchia?", opts: ['Dracma', 'Lira turca', 'Dinar', 'Piastre'], a: 1, diff: 'medium', emoji: '🇹🇷' },
  { q: "Quale valuta usa la Corea del Sud?", opts: ['Yen', 'Yuan', 'Won', 'Baht'], a: 2, diff: 'medium', emoji: '🇰🇷' },
  { q: "Quale valuta usa la Polonia?", opts: ['Euro', 'Corona', 'Zloty', 'Fiorino'], a: 2, diff: 'medium', emoji: '🇵🇱' },
  { q: "In quale paese si trova Ayers Rock (Uluru)?", opts: ['Nuova Zelanda', 'Sud Africa', 'Australia', 'Namibia'], a: 2, diff: 'medium', emoji: '🪨' },
  { q: "Quale paese possiede le Isole Canarie?", opts: ['Portogallo', 'Francia', 'Marocco', 'Spagna'], a: 3, diff: 'medium', emoji: '🏝️' },
  { q: "Quale paese possiede le Isole Maldive?", opts: ['India', 'Sri Lanka', 'Maldive (stato indipendente)', 'Indonesia'], a: 2, diff: 'medium', emoji: '🏝️' },
  { q: "Qual è la moneta del Messico?", opts: ['Dolar', 'Real', 'Peso messicano', 'Quetzal'], a: 2, diff: 'medium', emoji: '🇲🇽' },
  { q: "Quale paese ha la bandiera con la stella e la mezzaluna bianca su rosso?", opts: ['Pakistan', 'Marocco', 'Turchia', 'Algeria'], a: 2, diff: 'medium', emoji: '🇹🇷' },
  { q: "In quale paese si trovano le Isole Galapagos?", opts: ['Perù', 'Colombia', 'Ecuador', 'Cile'], a: 2, diff: 'medium', emoji: '🦎' },
  { q: "Quale paese possiede la Groenlandia?", opts: ['Norvegia', 'Islanda', 'Svezia', 'Danimarca'], a: 3, diff: 'medium', emoji: '🧊' },
  { q: "In quale paese si trova il Kilimanjaro?", opts: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'], a: 2, diff: 'medium', emoji: '⛰️' },
  { q: "Qual è la capitale della Giamaica?", opts: ['Nassau', 'Kingston', 'Havana', 'Bridgetown'], a: 1, diff: 'medium', emoji: '🇯🇲' },
  { q: "Qual è la capitale di Malta?", opts: ['Mdina', 'Sliema', 'La Valletta', 'Gozo'], a: 2, diff: 'medium', emoji: '🇲🇹' },
  { q: "Quale aeroporto ha il codice IATA 'LHR'?", opts: ['Londra Gatwick', 'Londra Heathrow', 'Lisbona', 'Lussemburgo'], a: 1, diff: 'medium', emoji: '✈️' },
  { q: "Quale aeroporto ha il codice IATA 'MUC'?", opts: ['Madrid', 'Milano', 'Monaco di Baviera', 'Montréal'], a: 2, diff: 'medium', emoji: '✈️' },
  { q: "In quale paese si trova il deserto di Atacama?", opts: ['Messico', 'Cile', 'Australia', 'Marocco'], a: 1, diff: 'medium', emoji: '🌵' },
  { q: "Quale valuta si usa in Vietnam?", opts: ['Yuan', 'Baht', 'Dong', 'Riel'], a: 2, diff: 'medium', emoji: '🇻🇳' },
  { q: "In quale città si trova il famoso 'Muro del Pianto'?", opts: ['Amman', 'Il Cairo', 'Gerusalemme', 'Beirut'], a: 2, diff: 'medium', emoji: '🕍' },
  { q: "Qual è la capitale dell'Austria?", opts: ['Vienna', 'Salisburgo', 'Innsbruck', 'Graz'], a: 0, diff: 'medium', emoji: '🇦🇹' },
  { q: "Quale isola è divisa tra Indonesia, Malaysia e Brunei?", opts: ['Giava', 'Sumatra', 'Borneo', 'Nuova Guinea'], a: 2, diff: 'medium', emoji: '🏝️' },
  { q: "Quale paese possiede l'Isola di Pasqua?", opts: ['Perù', 'Cile', 'Australia', 'Nuova Zelanda'], a: 1, diff: 'medium', emoji: '🗿' },
  { q: "Qual è la capitale della Slovacchia?", opts: ['Lubiana', 'Bratislava', 'Praga', 'Budapest'], a: 1, diff: 'medium', emoji: '🇸🇰' },
  // ─────────────────────────────────────────────────────────────────────────
  // HARD — Capitali oscure & fatti geografici rari
  // ─────────────────────────────────────────────────────────────────────────
  { q: "Qual è la capitale del Bhutan?", opts: ['Kathmandu', 'Thimphu', 'Paro', 'Punakha'], a: 1, diff: 'hard', emoji: '🇧🇹' },
  { q: "Qual è la capitale del Myanmar?", opts: ['Yangon', 'Mandalay', 'Naypyidaw', 'Bagan'], a: 2, diff: 'hard', emoji: '🇲🇲' },
  { q: "Qual è la vera capitale dell'Australia?", opts: ['Sydney', 'Melbourne', 'Brisbane', 'Canberra'], a: 3, diff: 'hard', emoji: '🇦🇺' },
  { q: "Qual è la capitale del Kazakhstan?", opts: ['Almaty', 'Shymkent', 'Astana', 'Aktau'], a: 2, diff: 'hard', emoji: '🇰🇿' },
  { q: "Qual è la capitale dell'Uzbekistan?", opts: ['Samarcanda', 'Bukhara', 'Tashkent', 'Namangan'], a: 2, diff: 'hard', emoji: '🇺🇿' },
  { q: "Qual è la capitale della Mongolia?", opts: ['Ulaangom', 'Erdenet', 'Ulan Bator', 'Darkhan'], a: 2, diff: 'hard', emoji: '🇲🇳' },
  { q: "Qual è la capitale della Mozambico?", opts: ['Beira', 'Nampula', 'Maputo', 'Tete'], a: 2, diff: 'hard', emoji: '🇲🇿' },
  { q: "Qual è la capitale di Papua Nuova Guinea?", opts: ['Lae', 'Mount Hagen', 'Madang', 'Port Moresby'], a: 3, diff: 'hard', emoji: '🇵🇬' },
  { q: "Qual è la capitale dell'Islanda?", opts: ['Akureyri', 'Keflavík', 'Reykjavík', 'Hafnarfjörður'], a: 2, diff: 'hard', emoji: '🇮🇸' },
  { q: "Qual è la capitale della Bolivia?", opts: ['La Paz e Sucre', 'Santa Cruz', 'Cochabamba', 'Oruro'], a: 0, diff: 'hard', emoji: '🇧🇴' },
  { q: "Qual è la capitale del Kosovo?", opts: ['Prizren', 'Peja', 'Pristina', 'Mitrovica'], a: 2, diff: 'hard', emoji: '🇽🇰' },
  { q: "Qual è la capitale del Laos?", opts: ['Luang Prabang', 'Vientiane', 'Pakse', 'Savannakhet'], a: 1, diff: 'hard', emoji: '🇱🇦' },
  { q: "Qual è la capitale dell'Oman?", opts: ['Salalah', 'Sohar', 'Mascate', 'Nizwa'], a: 2, diff: 'hard', emoji: '🇴🇲' },
  { q: "Qual è la capitale della Georgia (paese)?", opts: ['Batumi', 'Kutaisi', 'Tbilisi', 'Rustavi'], a: 2, diff: 'hard', emoji: '🇬🇪' },
  { q: "Qual è la capitale dell'Armenia?", opts: ['Gyumri', 'Vanadzor', 'Erevan', 'Abovyan'], a: 2, diff: 'hard', emoji: '🇦🇲' },
  // HARD — Aeroporti & IATA
  { q: "Qual è l'aeroporto più trafficato del mondo?", opts: ['Dubai DXB', 'Londra LHR', 'Atlanta ATL', 'Beijing PEK'], a: 2, diff: 'hard', emoji: '🛫' },
  { q: "Quale aeroporto ha il codice IATA 'NRT'?", opts: ['Seoul', 'Shanghai', 'Tokyo Narita', 'Singapore'], a: 2, diff: 'hard', emoji: '✈️' },
  { q: "Quale aeroporto ha il codice IATA 'SIN'?", opts: ['Sydney', 'Seoul', 'Shanghai', 'Singapore'], a: 3, diff: 'hard', emoji: '✈️' },
  { q: "Quale aeroporto ha il codice IATA 'GRU'?", opts: ['Buenos Aires', 'Lima', 'Bogotà', 'São Paulo'], a: 3, diff: 'hard', emoji: '✈️' },
  { q: "Quale aeroporto ha il codice IATA 'HND'?", opts: ['Hanoi', 'Hong Kong', 'Tokyo Haneda', 'Ho Chi Minh'], a: 2, diff: 'hard', emoji: '✈️' },
  { q: "Quale aeroporto ha il codice IATA 'MEX'?", opts: ['Miami', 'Madrid', 'Melbourne', 'Città del Messico'], a: 3, diff: 'hard', emoji: '✈️' },
  { q: "Quale compagnia ha il codice IATA 'SQ'?", opts: ['South African', 'Swiss', 'Saudia', 'Singapore Airlines'], a: 3, diff: 'hard', emoji: '✈️' },
  { q: "Quale compagnia ha il codice IATA 'CX'?", opts: ['China Eastern', 'China Southern', 'Cathay Pacific', 'China Airlines'], a: 2, diff: 'hard', emoji: '✈️' },
  { q: "Quale compagnia aerea è la più antica ancora operativa?", opts: ['Qantas', 'KLM', 'Lufthansa', 'British Airways'], a: 1, diff: 'hard', emoji: '✈️' },
  // HARD — Geografia avanzata
  { q: "Il Bosforo attraversa quale città?", opts: ['Atene', 'Sofia', 'Beirut', 'Istanbul'], a: 3, diff: 'hard', emoji: '🌉' },
  { q: "La bandiera del Nepal è l'unica al mondo che non è rettangolare: è a forma di…", opts: ['Triangolo', 'Esagono', 'Doppio triangolo', 'Croce'], a: 2, diff: 'hard', emoji: '🇳🇵' },
  { q: "Quanti paesi fanno parte dell'Unione Europea?", opts: ['25', '26', '27', '28'], a: 2, diff: 'hard', emoji: '🇪🇺' },
  { q: "Come si chiama la valuta dell'Islanda?", opts: ['Corona danese', 'Króna islandese', 'Euro', 'Corona norvegese'], a: 1, diff: 'hard', emoji: '🇮🇸' },
  { q: "Quale paese africano non è mai stato completamente colonizzato?", opts: ['Ghana', 'Etiopia', 'Senegal', 'Tanzania'], a: 1, diff: 'hard', emoji: '🌍' },
  { q: "Quale oceano ha la temperatura superficiale media più alta?", opts: ['Pacifico', 'Atlantico', 'Indiano', 'Artico'], a: 2, diff: 'hard', emoji: '🌡️' },
  { q: "In quale paese si trova il Monastero di Meteora?", opts: ['Albania', 'Bulgaria', 'Serbia', 'Grecia'], a: 3, diff: 'hard', emoji: '⛪' },
  { q: "Quale paese ha la bandiera completamente bianca con stemma?", opts: ['Vaticano', 'Monaco', 'Andorra', 'San Marino'], a: 0, diff: 'hard', emoji: '🇻🇦' },
  { q: "Quale è il paese più piccolo del mondo?", opts: ['Monaco', 'San Marino', 'Liechtenstein', 'Città del Vaticano'], a: 3, diff: 'hard', emoji: '🗺️' },
  { q: "Quale monte è il più alto fuori dall'Asia?", opts: ['Kilimanjaro', 'Mont Blanc', 'Aconcagua', 'Denali'], a: 2, diff: 'hard', emoji: '⛰️' },
  { q: "Quale lago è il più profondo del mondo?", opts: ['Lago Superiore', 'Mar Caspio', 'Lago Baikal', 'Lago Victoria'], a: 2, diff: 'hard', emoji: '🏞️' },
  { q: "Quale paese ha il maggior numero di lingue ufficiali?", opts: ['India', 'Svizzera', 'Sud Africa', 'Bolivia'], a: 2, diff: 'hard', emoji: '🗣️' },
  { q: "Quale è il paese con la costa più lunga del mondo?", opts: ['Russia', 'Australia', 'Norvegia', 'Canada'], a: 3, diff: 'hard', emoji: '🌊' },
  { q: "Quale canale artificiale unisce il Mar Rosso al Mar Mediterraneo?", opts: ['Canale di Panama', 'Canale di Suez', 'Canale di Corinto', 'Canale di Kiel'], a: 1, diff: 'hard', emoji: '🚢' },
  { q: "Quale stato USA si trova fuori dal continente nordamericano?", opts: ['Alaska', 'Hawaii', 'Alaska e Hawaii', 'Puerto Rico'], a: 2, diff: 'hard', emoji: '🌺' },
  { q: "Quale paese ha la valuta chiamata 'Krone' o 'Krone'?", opts: ['Solo Danimarca', 'Solo Norvegia', 'Danimarca, Norvegia e Svezia', 'Solo Svezia'], a: 2, diff: 'hard', emoji: '💰' },
  { q: "Quale città ospita il Museo del Louvre?", opts: ['Bruxelles', 'Londra', 'Parigi', 'Berlino'], a: 2, diff: 'hard', emoji: '🏛️' },
  { q: "Quale è la città più meridionale d'Europa?", opts: ['Lampedusa (IT)', 'Tarifa (ES)', 'Valletta (MT)', 'Heraklion (GR)'], a: 1, diff: 'hard', emoji: '🌍' },
  { q: "Quale stretto separa la Sicilia dalla Tunisia?", opts: ['Stretto di Messina', 'Stretto di Gibilterra', 'Stretto di Sicilia', 'Canale di Sardegna'], a: 2, diff: 'hard', emoji: '🌊' },
  { q: "Qual è la capitale del Montenegro?", opts: ['Cetinje', 'Podgorica', 'Budva', 'Kotor'], a: 1, diff: 'hard', emoji: '🇲🇪' },
  { q: "Qual è la capitale del Suriname?", opts: ['Georgetown', 'Paramaribo', 'Cayenne', 'Belmopan'], a: 1, diff: 'hard', emoji: '🇸🇷' },
  { q: "Qual è la capitale dell'Eritrea?", opts: ['Asmara', 'Massaua', 'Assab', 'Keren'], a: 0, diff: 'hard', emoji: '🇪🇷' },
  { q: "Quale paese ha un fucile AK-47 sulla sua bandiera?", opts: ['Angola', 'Mozambico', 'Zimbabwe', 'Haiti'], a: 1, diff: 'hard', emoji: '🇲🇿' },
  { q: "In quale paese si trova la cascata più alta del mondo (Salto Angel)?", opts: ['Brasile', 'Guyana', 'Venezuela', 'Colombia'], a: 2, diff: 'hard', emoji: '🌊' },
  { q: "Quale aeroporto ha il codice IATA 'BKK'?", opts: ['Beijing', 'Bangkok Suvarnabhumi', 'Brisbane', 'Baku'], a: 1, diff: 'hard', emoji: '✈️' },
  { q: "Quale aeroporto ha il codice IATA 'KUL'?", opts: ['Kochi', 'Kunming', 'Kuala Lumpur', 'Karachi'], a: 2, diff: 'hard', emoji: '✈️' },
  { q: "Qual è la capitale del Madagascar?", opts: ['Antananarivo', 'Toamasina', 'Mahajanga', 'Antsirabe'], a: 0, diff: 'hard', emoji: '🇲🇬' },
  { q: "Qual è la capitale del Paraguay?", opts: ['Asunción', 'Ciudad del Este', 'Encarnación', 'Luque'], a: 0, diff: 'hard', emoji: '🇵🇾' },
  { q: "In quale paese si trova la regione della Transilvania?", opts: ['Ungheria', 'Romania', 'Bulgaria', 'Moldavia'], a: 1, diff: 'hard', emoji: '🧛' },
  { q: "Qual è la capitale della Sierra Leone?", opts: ['Freetown', 'Conakry', 'Monrovia', 'Dakar'], a: 0, diff: 'hard', emoji: '🇸🇱' },
  { q: "Quale nazione ha il maggior numero di fusi orari (includendo territori d'oltremare)?", opts: ['Russia', 'USA', 'Francia', 'Cina'], a: 2, diff: 'hard', emoji: '⏰' },
  { q: "Qual è la capitale del Tagikistan?", opts: ['Bishkek', 'Ashgabat', 'Dushanbe', 'Tashkent'], a: 2, diff: 'hard', emoji: '🇹🇯' },
  { q: "Qual è l'unico paese al mondo ad avere una bandiera quadrata (oltre al Vaticano)?", opts: ['Svizzera', 'Belgio', 'Lussemburgo', 'Monaco'], a: 0, diff: 'hard', emoji: '🇨🇭' },
  { q: "In quale paese si trova la città più antica del mondo ancora abitata (Damasco)?", opts: ['Iraq', 'Egitto', 'Siria', 'Giordania'], a: 2, diff: 'hard', emoji: '🇸🇾' },
];
